[workspace]
members = [
    "aoc_macros",
    "aoc_framework",
    "aoc_utils",
    "puzzles/year2015",
    "puzzles/year2021",
    "puzzles/year2022",
    "puzzles/year2023",
    "aoc_runner",
]
resolver = "2"
